apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MagicChessBoard
  annotations:
    github.com/project-slug: bjornallvin/MagicChessBoard
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: guests
